// <auto-generated />
namespace MarketPlace.WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FullDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FullDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201612281626223_Full DB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
