// <auto-generated />
namespace MarketPlace.WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class SecondFinalDBStructuremaybe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SecondFinalDBStructuremaybe));
        
        string IMigrationMetadata.Id
        {
            get { return "201701062204000_SecondFinalDBStructure(maybe)"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
